### ISSUE TITLE
Suggestion: Simplify nav window UI icons

### ISSUE THREAD

**Issue by ainsley** [asciidocfx/AsciidocFX#107]
(moved this from #105 as it was unrelated to that issue)

Suggestion -- Not Bug
----

A request here is that the home button is replaced by the a favourite directories dropdown. The home button is pretty redundant really because it navigates to the user home folder, and quite often a project folder is deep underneath this folder, or on an entirely different drive entirely. It's better than C drive - which is Windows-centric, and its maybe (or maybe not depending on the project layout of the particular user) better than device root ( / or drive selection screen), because there might be a lot of drilling down going on here, but it is still sub-optimal as it assumes that all documentation is underneath the user folder - which is not an entirely safe assumption. Favourite folders takes the guesswork out of navigation defaults.

But, home is useful in certain cases, so just have home as a fixed "favourite folder" that cannot be deleted, at the top, and place the favourite folder list directly underneath home in the dropdown from the navigator window. That is, favourite folders on the submenu is cumbersome to use (you have to right click somewhere, then select the option, then select the folder -- 3 interactions including some precision mouse movement). Better that the favourite folders is where the home button is now. You could add an additional button next to home just for favourite folders, but I think that home and favourite folders are the same thing really, so merging the UI item makes more sense navigationally speaking.

![action bar](https://cloud.githubusercontent.com/assets/201870/8758883/d41cbbfe-2ce1-11e5-8144-9eea8b8bf8b4.png)

-----

Sorry if I appear to opinionated. Feel free to ignore everything if you wish ... but I hope that I have at least articulated and justified why I feel it might a good idea to modify the UI aspects of the favourite directory feature, and perhaps the navigation panel in general.

**Comment by rahmanusta** [comment]
@takapa Maybe you have a large screen, but generally in my screen it seems below;

![asciidocfx](https://cloud.githubusercontent.com/assets/1158804/9170968/405b4cea-3f70-11e5-8336-5e4f7a5eb4d9.png)

For the suggestion, I only removed up go button, because we can go up by doubleclicking to root.

**Comment by takapa** [comment]
My own subjective opinion is that the two drop-downs are still a problem. I'm a big fan of AsciiDocFX, however I struggle to instinctively remember where to find the options I'm looking for. If I can't train my instinct after weeks of use, then my gut feeling is that the UI is too complex.

Also - tricks like double clicking the root to go up a folder, are fine, but they are not obvious to new users and they are absolutely opposite to the UI conventions of every popular OS in use today. It's the equivalent to switching around Ctrl+C and Ctrl+V keyboard short-cuts. Not only does it slow you down, but it will lead to erroneous inputs. It slows the UI flow down to pause and think about how to navigate up a folder rather than instinctively clicking "..: or an Up Arrow. You have space on the icon bar, or space at the top of the folder view, so either an up or back button or a ".." option underneath the current folder is a better approach, because it doesn't require any thought by the user. They are used to navigating in this way without knowing about secret click events.

Again - big fan here, but the UI options really need some work as there are just too many places where configuration takes place now:

Such as

* Right click on render window to toggle rendering on/off.
* Some keypress to get up editor settings (I forgot the keypress already)
* Icons above the file viewer to toggle various settings.
* Access favourites list by right clicking inside explorer window.
* Options hidden in editing pane without clicking downward.
* Right click editor tab to get (Go to workdir or open file location)

I love options, options are great, but it is seriously disorientating to have settings hidden beneath right click context menus everywhere. I don't have a problem with right click context menus either - I like them - I really like them, and I wouldn't suggest getting rid of any of the ones you have already - they are well designed. But you shouldn't lean on distributed options. Microsoft office has context sensitive menus for almost everything, but there was also a menu at the top of the screen which could be used to find options quickly too (pre-ribbon). My strong personal belief is that there should be a common place to access settings at the header of the appropriate location, and there should be a maximum of one generic dropdown per section (an icon without corresponding on-screen textual description). If you have two dropdowns, without text, and without clear iconic meaning, then it is confusing in the extreme, and you end up clicking both options to find what you are looking for, and if it is hidden in a context sensitive submenu, you won't even find what you were looking for even after exploring two separate dropdowns.

All this is low priority of course, AsciiDocFX is ultra useful even with slightly obscure UI navigation. I just want to make a point that the UI could do with a bit of touch-up when time permits.

Chris

P.S. I love AsciDocFX, it is an amazing application.

**Comment by rahmanusta** [comment]
We simplified UI in v1.4.1 @ainsley
