### ISSUE TITLE
UML rendered as "link" when scrolling with cursor

### ISSUE THREAD

**Issue by ahus1** [asciidocfx/AsciidocFX#144]
When I type the rendering of UML is fine. 

Once I use the cursor and scroll through the document (i.e. placing the cursor) the includes are not evaluated (?)

Due to this the follwing code

```
["plantuml", "overview", "png"]
--
include::overview.puml[]
--
```

renders the following image when scrolling

![link](https://cloud.githubusercontent.com/assets/3957921/9847472/5c73e99e-5ad9-11e5-8a49-c7916c0caf93.png)

and the correct UML when typing again

![nginx](https://cloud.githubusercontent.com/assets/3957921/9847490/7d1a500c-5ad9-11e5-8669-b0683e7d13c1.png)

(tested with version 1.3.8)

**Comment by rahmanusta** [comment]
@ahus1 It is interesting, I really dont know why it produces it as link when clicking include directive. However we need to solve it.

**Comment by rahmanusta** [comment]
@ozlerhakan May it be about click jumping resolver ?

**Comment by ozlerhakan** [comment]
I am not 100% sure but it might be related to the plantUml method of PlantUmlService. When we move the cursor over the mentioned snippet, [findRenderedSelection](https://github.com/asciidocfx/AsciidocFX/blob/90ca352869bab541d1802b4b2e57b357db634e21/conf/public/js/converters.js#L54) function is triggered and likewise asciidoctor-uml-block.js starts running 

The following code returns from asciidoctor-uml-block.js when we move the cursor:
```
[plantuml, "overview", "png"]
--
include::overview.puml[]
--
```
Since the plantUml method eventually is called due to asciidoctor-uml-block.js , this method again generates a new image in terms of the code with the same image path.

```
@startuml

skinparam dpi 300
[plantuml, "overview", "png"]
--
include::overview.puml[]
--
@enduml
```

![link](https://cloud.githubusercontent.com/assets/3957921/9847472/5c73e99e-5ad9-11e5-8a49-c7916c0caf93.png)

I found out 2 approaches to fix it, we need to:

1. stop going into the platuml method when we move the cursor (same for changing scroll), may be needed an additional variable to check or
2.  search `include::`  and find the corresponding content of this file and replace it with the include directive to generate the same image again and again.

wdyt kardeşim?

**Comment by rahmanusta** [comment]
@ahus1 Could you try v1.3.9 ?
