### ISSUE TITLE
Creating pdf, footnotes overwrite bottom of page

### ISSUE THREAD

**Issue by russurquhart1** [asciidocfx/AsciidocFX#162]
The attached file, when i try to generate pdf, the footnotes overwrite the bottom of the page, and text underdeath!
<img width="702" alt="screen shot 2015-10-30 at 10 47 01 am" src="https://cloud.githubusercontent.com/assets/1834016/10850992/827c455a-7ef6-11e5-9bb2-50ae8d599e57.png">

**Comment by nerk** [comment]
I just investigated into the same issue. It's an old bug in Apache FOP regarding the calculation of spacing around list items. As a workaround, you can change the block 

```
<xsl:attribute-set name="list.item.spacing">
        <xsl:attribute name="space-before.optimum">0.5em</xsl:attribute>
        <xsl:attribute name="space-before.minimum">0.2em</xsl:attribute>
        <xsl:attribute name="space-before.maximum">0.8em</xsl:attribute>
 </xsl:attribute-set>
```

in file asciidocfx/AsciidocFX/conf/docbook-config/fo-pdf.xsl as follows:

```
<xsl:attribute-set name="list.item.spacing">
        <xsl:attribute name="space-before.optimum">0.4em</xsl:attribute>
        <xsl:attribute name="space-before.minimum">0.4em</xsl:attribute>
        <xsl:attribute name="space-before.maximum">0.4em</xsl:attribute>
 </xsl:attribute-set>
```

Disclaimer: Since I am not using AsciidocFX, I did not try this directly with AsciidocFX but in a different environment.

**Comment by rahmanusta** [comment]
Thank you @nerk I will update our config list item config as your feedback :+1:

**Comment by nerk** [comment]
I think there is also a compact version of lists with its own configuration. You may want to change this accordingly, if required. The important thing is that all attributes within the set must  have the same value.
