### ISSUE TITLE
Autosave option

### ISSUE THREAD

**Issue by NicolasGeraud** [asciidocfx/AsciidocFX#167]
Because with the autoupdate option we have a very fluent writing workflow, it could be nice to add an "Auto save" option in Editor Settings.

With this option, we just have to think about writing, not saving.

**Comment by rahmanusta** [comment]
@NicolasGeraud  Hmm, when you close any tab or application, it will save document(s) by default. Does it mean what you want?

**Comment by NicolasGeraud** [comment]
No,
I use intellij in my daily work, and it saves my work in background. No more Ctrl+S .

Actually I write a long document, and I have to not forget to save my file if a crash occurs or a battery failure.

**Comment by rahmanusta** [comment]
You dont need to use ctrl+s in afx. But jvm crash or battery failure causes to data lost. We are imitating intellij idea' saving behaviour. Are you sure intellij saves your data if crash or battery failure occurs?

**Comment by rahmanusta** [comment]
@NicolasGeraud what do you think about AsciidocFX's saving behaviours ?

**Comment by kenokabe** [comment]
@rahmanusta I think the suggestion by @NicolasGeraud perfectly makes sense. You are right in the sense that the sudden crash causes the data lost in any way, but data edited 10seconds ago will be saved if autosaved 10 seconds ago, and it's very unlikely to save the data frequently manually without the writer consumes his performance just to save the data. I think most of the modern editor has an auto-save feature as the default, not as an option. 

What do you lose by the simple implementation of such an important feature? In fact, I am another guy who googled to make sure this nice editor has the auto-save feature, and now I'm a bit of surprised have found it to be ignored.

Thanks.

**Comment by rahmanusta** [comment]
Hi @kenokabe, I'm open for contribution and pull requests

**Comment by kenokabe** [comment]
@rahmanusta Hi, thanks a lot to have reopened the issue. Let me correct my prior mention:

>most of the modern editors have an auto-save feature as the default, not as an option.

 For Microsoft Officce Suite. it should be true:
https://support.office.com/en-us/article/what-is-autosave-6d6bd723-ebfd-4e40-b5f6-ae6e8088f7a5

>What is AutoSave?
>"Save early, save often" is now a thing of the past. Now there's AutoSave which saves every few seconds so that you don't have to.
>AutoSave is enabled when a file is stored on OneDrive, OneDrive for Business, or SharePoint Online. It automatically saves your changes to the cloud as you are working. And, if other people are working on the same file, AutoSave lets them see your changes in a matter of seconds.

For Microsoft VisualStudio Code which I heavily use, it is an option:
https://code.visualstudio.com/docs/editor/codebasics#_save-auto-save
>Save / Auto Save
>By default, VS Code requires an explicit action to save your changes to disk, Ctrl+S.
>However, it's easy to turn on Auto Save, which will save your changes after a configured delay or when focus leaves the editor. With this option turned on, there is no need to explicitly save the file. The easiest way to turn on Auto Save is with the File > Auto Save toggle which turns on and off save after a delay.
>For more control over Auto Save, open User or Workspace settings and find the associated settings:
>files.autoSave: Can have the values:
- off - to disable auto save.
- afterDelay - to save files after a configured delay (default 1000 ms).
- onFocusChange - to save files when focus moves out of the editor of the dirty file.
- onWindowChange - to save files when the focus moves out of the VS Code window.
-  files.autoSaveDelay: Configures the delay in milliseconds when files.autoSave is configured to afterDelay. The default is 1000 ms.

I personally use VSCode auto-save  `onFocusChange` because the auto-format of the code is also depends on the save. Eitherway, nowadays looks like auto-save on the spot or every few seconds seems an established manner, and since I probably keep using this nice editor, I hope this one also behaves in that manner to avoid the data loss.  I wish I could help this issue, but unfortunately I'm JavaScript coder.

**Comment by rahmanusta** [comment]
Thanks for the details. I think this can be implemented, but I don't know when.. Btw, onFocusChange  and onWindowChange  is default behaviour of AsciidocFX.

**Comment by kenokabe** [comment]
@rahmanusta 

Thanks for this nice editor again. I think this editor is the best in this AsciiDoc world.

>Btw, onFocusChange and onWindowChange is default behaviour of AsciidocFX.

Yesterday, I start writing on this editor and found that `include` does not reflect the preview for the included another file with a change. It may be saved onFocusChnage (of tab), but the multiple file's changes do not integrate well. Just let you know. At that time, I thought it must be saved manually.

**Comment by rahmanusta** [comment]
We long time auto-saving files in AsciidocFX
