### ISSUE TITLE
Paste image/screenshot from Windows Clipboard.

### ISSUE THREAD

**Issue by bwklein** [asciidocfx/AsciidocFX#219]
The only feature of MS Word that my end users of AsciidocFX complain about is the inability to do the old alt+printscr to capture the screen image and then paste it into Word.

I am thinking of a feature that allows for an image file or clipboard image to be pasted into AsciidocFX.

On paste (ctrl+v), the image would be turned into a png file that would be saved into the default images directory.  At the cursor position, there would be an image reference similar to what we see now when we drag an image out of the file tree and into the editor.

This would change how many people see the ease of use and adoption of text based document formats like AsciiDoc.

**Comment by mojavelinux** [comment]
:+1: I think this is a key feature towards the goal of an "IDE for writers". Specifically, it addresses a workflow. Instead of making the author copy an image to the images directory, then typing (or auto-completing) that image path in an image macro, all that work is hidden behind a drag-and-drop operation. We capture the author's intent and can automate the steps that the author would otherwise have to do.

**Comment by rahmanusta** [comment]
Hi @bwklein @mojavelinux , it is a good feature request. I will look at that, it is in the queue. Thanks.

**Comment by bwklein** [comment]
@rahmanusta Please see the Atom Package that I forked and converted over to support AsciiDoc.  This is some of the functionality that would be nice to have in AsciidocFX.
https://atom.io/packages/asciidoc-image-helper

**Comment by rahmanusta** [comment]
Please try version 1.4.6 https://github.com/asciidocfx/AsciidocFX/releases/tag/v1.4.6

I now close this issue, if you think your issue is not fixed, please don't hesitate to reopen or comment the issue.
