### ISSUE TITLE
asciisocFx.exe is not a Win32 application

### ISSUE THREAD

**Issue by lit-uriy** [asciidocfx/AsciidocFX#223]
I get this message when trying run the installer on your Windows XP. Please help me to install the program on Windows XP.

**Comment by rahmanusta** [comment]
AsciidocFX doesn't release 32bit release, you should do it manually or wait this feature in new release.

**Comment by rahmanusta** [comment]
Please try version 1.4.6 https://github.com/asciidocfx/AsciidocFX/releases/tag/v1.4.6

You should use asciidocfx-1.4.6.zip or platform dependent release with NO_JRE. You should have at least jre 1.8.0 u80

I now close this issue, if you think your issue is not fixed, please don't hesitate to reopen or comment the issue.
