### ISSUE TITLE
ASF 1.4.9 Application Hanging

### ISSUE THREAD

**Issue by rich4j** [asciidocfx/AsciidocFX#247]
Hi there

After upgrading to 1.4.9 the application seems to have become laggy. AsciidocFx frozen a number of times and the editor becomes unresponsive after I close the editor. It subsequently does not open .adoc files. Attaching my log and a threaddump

Let me know if I can provide more info?

Thanks

Rich

[ascdiidoc-threadsump.txt](https://github.com/asciidocfx/AsciidocFX/files/471705/ascdiidoc-threadsump.txt)

[asciidocfx-log.txt](https://github.com/asciidocfx/AsciidocFX/files/471698/asciidocfx-log.txt)

**Comment by rahmanusta** [comment]
@rich4j

Which OS do you use?
When does it become unresponsive?
For a short investigation can you detect which method hangs with a profiler?
Which JRE do you use ? A bundle one?

Thanks for reporting

**Comment by peterrogers68** [comment]
Hi, I would like to pick up on this bug report, I upgraded to version 1.4.9 and have a problem with the application becoming unresponsive it almost always happens when for example I tab across lets say to my email and then return to AsciiFx the screen is sometimes black it then after a few seconds dispalys the document I'm coding but the page is frozen and I have to close and re-open.
I'm using windows 7 Pro 
Let me know if you need any further info or if anything is unclear, I really love using this editor but today its driving me crazy

**Comment by wfouche** [comment]
@peterrogers68  You might want to consider using an older version of AsciidocFX in the meantime. I've switched back to v1.4.6, and it works fine and is stable on all the documents that I've created. Later versions have one or more bugs that prevent them from working correctly with my documents. I'm sure these issues will be resolved overtime in 1.4.{10,11, ...}.

**Comment by rahmanusta** [comment]
Hello folks, thanks for the reports. I have just released v1.5.0, can you test it? Some bugs may come from me and some may come from JDK 1.8.0_102, let's find problems Thank you.
