### ISSUE TITLE
image:: does not render

### ISSUE THREAD

**Issue by seriouslyEnter** [asciidocfx/AsciidocFX#250]
Drag and Droping an image from the WorkDir View creates
image::imageOfSomething.PNG[]
which does not render in HTML
I have to manually remove one ":" to 
image:
then it works

I know ther is a difference between those two, documented here:  [http://asciidoctor.org/docs/user-manual/#images](url)

but only "image:" seems to work.

**Comment by rahmanusta** [comment]
double colon (::) means block image, single colon (:) means inline image. I tested it but it seems working. Could please share a screenshot with editor and preview were open to see this issue ?

Thanks

**Comment by seriouslyEnter** [comment]
I had trouble reproducing this error too.
But it seems to have something to do with "spaces" in filenames.
If there is no space in filename then (:) and (::) works fine.
If ther is space in filename only (:) works and (::) doesn't.

![screen shot](https://cloud.githubusercontent.com/assets/5265238/19015443/abe13280-8804-11e6-9e68-9f6bdc9d54ea.PNG)

**Comment by dewachterken** [comment]
I was able to reproduce the issue. The problem is that you include an image block (image::anything.png) inline (i.e. not as a block). 

You should either include the image as inline (image:anything.png) or include the image as a real block (preceded and following by a blank line).

This is a problem:
`This is an image::anything.png[]`

This is also a problem:
```
This is an
image::anything.png[]
```

This is not a problem:
`This is an image:anything.png[]`

This is also not a problem:
```
This is an

image::anything.png[]
```

**Comment by rahmanusta** [comment]
@dewachterken That is the correct explanation. Maybe we could add a line before adding blog image.

**Comment by seriouslyEnter** [comment]
I understand, thanks.
