### ISSUE TITLE
AFX 1.5.4 - several image files created for PlantUML diagram.

### ISSUE THREAD

**Issue by wfouche** [asciidocfx/AsciidocFX#266]
Hi @rahmanusta 

When changing the image filename of the diagram below from test00 to network-diagram

```
[plantuml, network-diagram, png]
----
@startdot
digraph G {
    node [shape=box]
	subgraph cluster_0 {
		node [style=filled];
		WIN_11 -> WIN_12 -> WIN_13;
		label = "WIN - Site 1";
		color = purple
	}

	subgraph cluster_1 {
		node [style=filled];
		WIN_21 -> WIN_22 -> WIN_23;
		label = "WIN - Site 2";
		color = purple
	}
	start -> WIN_11;
	start -> WIN_21;
	WIN_13 -> end;
	WIN_23 -> end;
    
    users [shape=Mdiamond]
    users -> start
    start [label="WIN_00", shape=invhouse]
	end [label="Peer-to-Peer\nReplication", shape=Msquare];
}
@enddot
----
```

several image files are created in quick succession as show below.

![clipboard01](https://cloud.githubusercontent.com/assets/13682850/20316114/3fe88e88-ab69-11e6-91a8-cfdc7d5da950.png)

AsciifocFX should ideally delete the current image file before creating a new image file for a particular diagram.

Thanks,

Werner

**Comment by rahmanusta** [comment]
Hi @wfouche, It is right but  there is no way to know which is last image name. Do you have any idea to implement it ?

**Comment by hesperaux** [comment]
Hi rahmanusta,
I will share a couple of ideas that I have, but they may not apply depending on your code.

I have not looked at the code, but is some event occurring when the text is changed for the file name? If so, does the event contain information about the filename before it was modified? If it did contain this information, you could simply delete the file pointed to by the old name before generating the new one, or you could open it, truncate it, store the image contents for the new UML diagram, and then rename the file. (This would make it easier on the filesystem not having to create lots of inodes)

Another suggestion:
Since the file has not changed (only its name is changing), why not do a fuzzy regex on the directory list, for items containing parts of the current filename, then take an md5 or sha1 hash of those files? Delete all files with the same SHA1 hash as the image you just generated. To make it simpler, maybe leave the regex off and do a full directory listing, but that will be slower (might be able to optimize if you can isolate the particular file group that is the same).

Another way to isolate the files is to sort by byte size. All items with the same byte size, take their SHA1 and compare to the latest image file.

I understand this has to happen for every onkeydown event, but right now you are creating lots of inodes anyway.

**Comment by wfouche** [comment]
Dropped.
