### ISSUE TITLE
Feature request: Inline math

### ISSUE THREAD

**Issue by xsrvmy** [asciidocfx/AsciidocFX#304]
Right now, to generate insert math in the document, one uses the latexmath: command. Is it possible to add mathjax to the output/preview file so that math can be inserted with \(\) and \[\]? I believe stock asciidoctor does that.

**Comment by rahmanusta** [comment]
Could you please give an example for that?

2017-05-09 22:50 GMT+03:00 xsrvmy <notifications@github.com>:

**Comment by xsrvmy** [comment]
Oops... I meant `\(...\)` and `\[...\]`.
Actually, I don't think asciidoctor export uses mathjax. However, the preview plugin on chrome does use mathjax.
For example, just try the following in a file
```
\(x^2\)
```

which should read x squared

**Comment by xsrvmy** [comment]
Never mind. I didn't know about :stem: option

**Comment by RoyiAvital** [comment]
Why the MathJax doesn't work on MarkDown?

**Comment by rahmanusta** [comment]
@RoyiAvital We have limited markdown support. You can use Asciidoc.

**Comment by RoyiAvital** [comment]
Could you enable $$...$$ and $...$ for AsciiDoc?

Moreover, it seems the ZIP version for Windows creates the Settings Files in the user folder instead of the program folder. Is there a way to fix it?

It also seems that version 1.5.5 form the site is signed (At least Windows 10 never complained about it) while version 1.5.6 from GitHub isn't signed and Windows 10 says it is from unknown publisher.
