### ISSUE TITLE
Bold monospace does not render.

### ISSUE THREAD

**Issue by dmd** [asciidocfx/AsciidocFX#60]
I tried:

    This is normal text. +This is monospace. *This is bold monospace.*+

Expected result: the described results. 
Actual result: All normal text, with literal asterisks around the final sentence. 

 The reference 'asciidoc' renderer supports this syntax.

**Comment by rahmanusta** [comment]
Please use like below;

```
This is normal text. `This is monospace. *This is bold monospace.*`
```

**Comment by dmd** [comment]
That syntax does not work in AsciidocFX 1.3.3. No bolding is done.

**Comment by rahmanusta** [comment]
It seems like working ?


![ddddd](https://cloud.githubusercontent.com/assets/1158804/6719285/2d8fb4ae-cdc2-11e4-8251-bca1e853c6f3.png)

**Comment by dmd** [comment]
![screenshot 2015-03-18 19 43 12](https://cloud.githubusercontent.com/assets/41439/6721760/1af17398-cda7-11e4-95b8-7bb00084fe73.png)

**Comment by rahmanusta** [comment]
This is interesting. @ozlerhakan What do you think?

**Comment by ozlerhakan** [comment]
Indeed interesting, since we know that AFX uses asciidoctor 1.5.2,  backtick is now used for monospace, not +.

we can still use + with the legacy mode like below:
![capture](https://cloud.githubusercontent.com/assets/1964927/6726807/42cfd94a-ce24-11e4-9f5f-515a14b253f6.PNG)

But, the think is that what @rahmanusta suggests does not work in your machine by default (interesting!). I do not know the reason for now.

**Comment by dmd** [comment]
Even compat-mode legacy doesn't work.
Note it works for me on OS X - just not on Linux.


![screenshot_1426777933](https://cloud.githubusercontent.com/assets/41439/6733502/ef467cde-ce28-11e4-8457-994072f6b186.png)

**Comment by rahmanusta** [comment]
Hey @mojavelinux. What do you think for this case?

**Comment by mojavelinux** [comment]
If it's just not working on Linux, it could be that the browser is just not displaying the bold font. The reason for that is that we are only loading Droid Sans Mono weight 400 from Google Fonts, not the bold version. The fix is to also load the bold font. I suppose we should add that to core. In the meantime, you can adjust the line that loads the fonts to include Droid Sans Mono 700.

```
https://fonts.googleapis.com/css?family=Open+Sans:300,300italic,400,400italic,600,600italic%7CNoto+Serif:400,400italic,700,700italic%7CDroid+Sans+Mono:400,700
```

**Comment by mojavelinux** [comment]
Added upstream: https://github.com/asciidoctor/asciidoctor/commit/d5862cf8da967ea4f58924d575ce52c3250ab3d7

**Comment by rahmanusta** [comment]
That can be styling issue as you said @mojavelinux . I'm seeing that Drid+Sans+Mono doesnt has 700. 

https://fonts.googleapis.com/css?family=Droid+Sans+Mono:400,700
